# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Study\python\video\video_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 750)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Study\\python\\video\\image/movie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mov_name = QtWidgets.QLineEdit(self.centralwidget)
        self.mov_name.setObjectName("mov_name")
        self.gridLayout.addWidget(self.mov_name, 0, 0, 1, 2)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 0, 2, 1, 1)
        self.download = QtWidgets.QPushButton(self.centralwidget)
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 0, 3, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 2, 0, 1, 1)
        self.show_mov = QtWidgets.QListWidget(self.centralwidget)
        self.show_mov.setObjectName("show_mov")
        self.gridLayout.addWidget(self.show_mov, 1, 0, 1, 4)
        self.open_path = QtWidgets.QPushButton(self.centralwidget)
        self.open_path.setObjectName("open_path")
        self.gridLayout.addWidget(self.open_path, 2, 3, 1, 1)
        self.save_path = QtWidgets.QPushButton(self.centralwidget)
        self.save_path.setObjectName("save_path")
        self.gridLayout.addWidget(self.save_path, 2, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 4, 0, 1, 4)
        self.dl_mov = QtWidgets.QLabel(self.centralwidget)
        self.dl_mov.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.dl_mov.setFont(font)
        self.dl_mov.setText("")
        self.dl_mov.setObjectName("dl_mov")
        self.gridLayout.addWidget(self.dl_mov, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "电影/电视剧下载"))
        self.search.setText(_translate("MainWindow", "搜索"))
        self.download.setText(_translate("MainWindow", "下载"))
        self.checkBox.setText(_translate("MainWindow", "全选"))
        self.open_path.setText(_translate("MainWindow", "打开目录"))
        self.save_path.setText(_translate("MainWindow", "下载路径"))
